#!/bin/env bash

# Get the script directory.
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
# Include WriteLog function.
source "${SCRIPT_DIR}/inc/WriteLog.sh"

# Assemble the command path for Docker
CMD_PATH="$(cygpath -u "${PROGRAMFILES}\\Docker\\Docker\\resources\\bin\\docker.exe")"
# Check if the command exists.
if ! command -v "${CMD_PATH}" >/dev/null ; then
	WriteLog "Could not find a Docker installation!"
	read -r -p "Install Docker using WinGet? [y/N] " response
	if [[ "$response" =~ ^[yY]$ ]]; then
		winget install --disable-interactivity --accept-source-agreements --accept-package-agreements --exact --id "Docker.DockerDesktop"
	fi
	exit 1
else
	# Run the command in the background by default.
	"${CMD_PATH}" "$@"
fi
