#!/bin/bash

# "C:\Program Files\LockHunter\LockHunter.exe"

# Check if LockHunter is installed in the users 'lib' directory.
# shellcheck disable=SC2154
EXE_DIR="$(ls -d "$(cygpath -u "${ProgramW6432}")/LockHunter" 2> /dev/null)"
# Check if the PyCharm directory exists.
if [[ -d "${EXE_DIR}" ]] ; then
	cygstart --directory="${EXE_DIR}" LockHunter.exe "$@"
else
	echo "Could not find a LockHunter installation!"
	# read -r -p "Install LockHunter using WinGet? [y/N] " response.
	if [[ "$response" =~ ^[yY]$ ]]; then
		winget install --exact --id CrystalRich.LockHunter
	fi
	exit 1
fi
