#!/bin/bash

# shellcheck disable=SC2154
MSVS_BIN_DIR="$(ls -d "$(cygpath -u "${ProgramW6432}")/Microsoft Visual Studio/"*"/Community/Common"*"/IDE/")"

if [[ -d "${MSVS_BIN_DIR}" ]] ; then
	cygstart --directory="${MSVS_BIN_DIR}" "devenv.exe"
else
	echo "Could not find 'Visual Studio' directory in '${ProgramW6432}/Microsoft Visual Studio/*/Community/Common*/IDE)' !"
	exit 1
fi