#!/bin/bash

# Change also the working directory to prevent error on VCRUNTIME_xx.DLL.

cygstart --directory="$(cygpath "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE")" devenv.exe
