#!/bin/env bash
# Assemble the command path for Sublime text

# Windows location of pandoc.
EXE_BIN="$(cygpath -u "C:\Program Files\nodejs\node.exe")"

# Check if Node is installed.
if [[ ! -f "${EXE_BIN}" ]]; then
	# Install Node using winget locally.
	echo "Installing Node locally using WinGet."
	winget install --source winget --exact --id OpenJS.NodeJS
	# Double Check.
	if [[ ! -f "${EXE_BIN}" ]]; then
		echo "Installation of 'node' still not found after install!"
		exit 1
	fi
fi

# Run node with all this script's arguments.
"${EXE_BIN}" "$@"
