#!/bin/env bash
# Assemble the command path for Notepad++
CMD_PATH="$(cygpath -u "${PROGRAMFILES}\\Notepad++\\notepad++.exe")"
# Check if the command exists.
if ! command -v "${CMD_PATH}" 2>&1 /dev/null ; then
	echo "Notepad++ not installed at: ${CMD_PATH}"
  echo "Download from here: https://notepad-plus-plus.org/"
else
	# Run the command in the background by default.
	"${CMD_PATH}" "$@" &
fi