#!/bin/bash

CMD="nm"

# Check if the command is installed.
if ! [[ -x "$(command -v ${CMD})" ]]; then
  echo "Error: ${CMD} is not installed." >&2
  exit 1
fi

if [[ -z "$1" ]]; then
	echo "Usage: $0 <lib-file>"
	exit 1
fi

FILE="$(cygpath -w ${1})"

# Execute the command and remove duplicate lines and discard weak symbols.
#nm --demangle --defined-only --extern-only "${FILE}" | sort -r | uniq | sed -e '/^[0-9a-f]* [ARIDB] .*$/d'
# d000612.o:
nm --demangle --defined-only --extern-only "${FILE}" | sort -r | uniq | sed -e '/^[0-9a-f]* [ARIDB] .*$/d' | sed -e '/^d.*$/d'
#nm --demangle --defined-only --extern-only "${FILE}" | sort -r | uniq
#nm --demangle --dynamic --defined-only --extern-only "${1}" | uniq

