#!/bin/bash

CMD="nm"

# Check if the command is installed.
if ! [[ -x "$(command -v ${CMD})" ]]; then
	echo "Error: ${CMD} is not installed." >&2
	exit 1
fi

if [[ -z "$1" ]]; then
	echo "Usage: $0 <lib-file>"
	exit 1
fi


ext="$(echo "$1" | pcregrep -o1 '^.*\.(.*)$')"

case "${ext}" in
	a)
		nm -g "${1}" | c++filt  | sort -r | uniq | sed -e '/^[0-9a-f]* W .*$/d'
		;;
	so)
		nm --demangle --dynamic --defined-only --extern-only "${1}" | sort -r | uniq | sed -e '/^[0-9a-f]* W .*$/d'
		;;
	*)
		echo "Extension '.$ext' not implemented."
		;;
esac
