#!/bin/env bash
# Assemble the command path for Sublime text

CMD_PATH="$(cygpath -u "${PROGRAMFILES}\\Sublime Text\\sublime_text.exe")"

# Check if the command exists.
if ! command -v "${CMD_PATH}" 2>&1 /dev/null ; then
	echo "Sublime text not installed at: ${CMD_PATH}"
  echo "Download from here: 'https://www.sublimetext.com/' or install using 'winget install -e --id SublimeHQ.SublimeText.4'."
else
	# Run the command in the background by default.
	"${CMD_PATH}" "$@" &
fi
