#!/bin/env bash

if ! command -v "powershell" > /dev/null >/dev/null 2>&1 ; then
	echo "Powershell is not installed."
	exit 1
fi

# Set the profile path
profile_path="${USERPROFILE}/.profile"
if [[ -f "${profile_path}" ]]; then
	echo "Profile '${profile_path}' already exists."
else
	echo "Creating profile '${profile_path}'."
cat << 'EOF' > "${profile_path}"
#
# File for in Windows users directory 'C:\USERS\<user-name>\.profile'
#

# Correct the home directory.
export HOME="$(pwd)/cygwin"
# Move to the home directory and load the .bash_profile
cd
# Source the .bash_profile to have the same environment as Cygwin gets on the system itself.
source .bash_profile
EOF
fi

# Form powershell script.
ps_script="${BASH_SOURCE[0]}.ps1"
# Call elevated powershell script.
if ! sudo powershell "$(cygpath -w "${BASH_SOURCE[0]}.ps1")" > /dev/null 2>&1 ; then
	echo "Executing elevated powershell script '${ps_script}' cancelled or failed!"
fi