#!/bin/bash

# Bailout when no arguments are passed.
if [ $# -ne 1 ] ; then
	echo "Is like 'ssh <user@server>' but passes the needed arguments for starting X-apps on the local X-server."
	exit 1
fi

# Check which X-server is running since the XWin server from Cygwin does not listen on a tcp-port but a socket.
if pidof XWin >/dev/null ; then
	# Run the ssh command passing the DISPLAY environment variable.
	echo ssh $* -Y -t "XCURSOR_SIZE=16 KDE_FULL_SESSION=true /bin/bash --login -i -c '$@'"
	ssh "${X_APP_USER}" -Y -t "XCURSOR_SIZE=16 KDE_FULL_SESSION=true /bin/bash --login -i "
else	
	# Get the VirtualBox Host-Only Ethernet Adapter IP address and only from the first one when more exist.
	IP_HOST_ONLY="$(ipconfig /all | grep "VirtualBox Host-Only Ethernet Adapter" -A 4 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | head -n 1)"
	# Check if the IP was retrieved.
	if [[ -z "${IP_HOST_ONLY}" ]]; then
		echo "The VirtualBox Host-Only Ethernet Adapter IP-address was not found!"
	else
		# Run the ssh command passing the DISPLAY environment variable.
		ssh $* -t "DISPLAY=${IP_HOST_ONLY}${DISPLAY} XCURSOR_SIZE=16 KDE_FULL_SESSION=true /bin/bash --login -c"
	fi	
fi
