#!/bin/bash

# Bailout when no arguments are passed.
if [ $# -ne 1 ] ; then
	ssh --help
	exit 1
fi

# Get the VirtualBox Adapters IP address.
IP_HOST_ONLY="$(ipconfig /all | grep "VirtualBox Host-Only Ethernet Adapter" -A 4 | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}')"

# Run the ssh command passing the DISPLAY environment variable based on the local DISPLAY variable.
ssh $* -t "DISPLAY=${IP_HOST_ONLY}${DISPLAY} KDE_FULL_SESSION=true XCURSOR_SIZE=16 /bin/bash --login"

